version: '3.8'

services:

  web:
    build: .
    command: ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://django_user:django_password@db:5432/django_db

